/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemindersIndexRouteImport } from './routes/reminders/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as InvoicesIdRouteImport } from './routes/invoices/$id'
import { Route as ClientsIdRouteImport } from './routes/clients/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIndexRoute = RemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/reminders/': typeof RemindersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/clients': typeof ClientsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/reminders': typeof RemindersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/reminders/': typeof RemindersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/clients/$id'
    | '/invoices/$id'
    | '/clients/'
    | '/invoices/'
    | '/reminders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/clients/$id'
    | '/invoices/$id'
    | '/clients'
    | '/invoices'
    | '/reminders'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/clients/$id'
    | '/invoices/$id'
    | '/clients/'
    | '/invoices/'
    | '/reminders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ClientsIdRoute: typeof ClientsIdRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  RemindersIndexRoute: typeof RemindersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/': {
      id: '/reminders/'
      path: '/reminders'
      fullPath: '/reminders/'
      preLoaderRoute: typeof RemindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ClientsIdRoute: ClientsIdRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  RemindersIndexRoute: RemindersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
